### ISSUE TITLE
Make optional parameters optional

### ISSUE THREAD

**Issue by bitstein** [willcl-ark/lnd_grpc#1]
Currently optional parameters are required. For instance:
```
def add_invoice(self, r_preimage: bytes, value: int, **kwargs):
        request = ln.Invoice(r_preimage=r_preimage, value=value, **kwargs)
        response = self.lightning_stub.AddInvoice(request)
        return response
```

`add_invoice` requires `r_preimage` but only `value` should be required.

**Comment by willcl-ark** [comment]
Thanks @bitstein, I have updated this on my local branch and will get it up into master ASAP

**Comment by willcl-ark** [comment]
Hi @bitstein, I've updated a fair bit on v0.2.2-beta now and it is in a much better state for testing. Either checkout v0.2.2-beta tag on GitHub if you are building from source, or a `pip install lnd_grpc --upgrade` should do the trick.

Let me know if you find any other issues. In the mean time, I am going to work on the asynchronous (non-blocking) RPC calls and getting some proper tests together.

**Comment by bitstein** [comment]
Hey @willcl-ark, looking great so far. There's another call that needs updating, but I think it might merit its own issue, so I'll be opening another. I'll link it here as well.
