### ISSUE TITLE
Add Support for Hodl invoices

### ISSUE THREAD

**Issue by dgnsrekt** [willcl-ark/lnd_grpc#21]
https://github.com/lightningnetwork/lnd/pull/2022

**Comment by dgnsrekt** [comment]
https://github.com/adrienemery/lnd-grpc-client/pull/13

**Comment by dgnsrekt** [comment]
Thanks for the hodl invoice support.
https://gist.github.com/dgnsrekt/52a845b95e3584a8dc7e1a50be6b5301

**Comment by willcl-ark** [comment]
Going to add some tests ASAP then get it (and loop) merged into master

**Comment by willcl-ark** [comment]
now merged into master
