### ISSUE TITLE
Not compatible with python 3.6

### ISSUE THREAD

**Issue by modenl** [willcl-ark/lnd_grpc#46]
The package now requires python>=3.7. Do we really need this?

**Comment by willcl-ark** [comment]
Hello @modenl, aside from syntactic sugar there is nothing specifically in there which requires 3.7 particularly. Which python version do you think we should target? Would 3.6 be low-enough or do you have some requirement to keep it at something lesser?

There is a new LND release every few months, so I didn't think it would be an unreasonable expectation that the sorts of people dealing with that, could install and use python 3.7 in a virtual environment if required, but totally understand it can be nuanced than that too!

If possible, my personal preference would be to keep using at least:

- PEP 498, formatted string literals.
- PEP 526, syntax for variable annotations.

from python 3.6, but of course, even those could be trimmed in theory if the need was there...

**Comment by willcl-ark** [comment]
Hello again @modenl, I have just analysed the code and it would only take 23 syntactic changes to get back to python 3.4 compatibility, would this work for your purposes do you think?

**Comment by modenl** [comment]
I am happy with python 3.6. Python 3.7 released last year which is too new for many projects. Thanks!

**Comment by willcl-ark** [comment]
works for me, I'm making the changes now

**Comment by willcl-ark** [comment]
merged
